// routes.go - 路由注册文件（自动生成，不建议手动编辑）
// 这个文件负责将所有 API 路由注册到 HTTP 服务器上
// 当请求到达服务器时，会根据 HTTP 方法和路径匹配对应的处理器

// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"greet/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

// RegisterHandlers - 注册所有路由处理器
// 这个函数在 main 函数中被调用，将所有定义的路由添加到服务器
// 参数：
//   - server: HTTP 服务器实例
//   - serverCtx: 服务上下文，包含配置和依赖服务
//
// 路由说明：
//   - GET /ping -> pingHandler: 当收到 GET /ping 请求时，会调用 pingHandler 处理
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,         // HTTP 方法：GET
				Path:    "/ping",                // 路由路径：/ping
				Handler: pingHandler(serverCtx), // 对应的处理器函数
			},
			{
				Method:  http.MethodGet,          // HTTP 方法：GET
				Path:    "/xufan",                // 路由路径：/ping
				Handler: xufanHandler(serverCtx), // 对应的处理器函数
			},
		},
	)
}
