// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: consumer.proto

package server

import (
	"context"

	"richcode.cc/dex/consumer/consumer"
	"richcode.cc/dex/consumer/internal/logic"
	"richcode.cc/dex/consumer/internal/svc"
)

type ConsumerServer struct {
	svcCtx *svc.ServiceContext
	consumer.UnimplementedConsumerServer
}

func NewConsumerServer(svcCtx *svc.ServiceContext) *ConsumerServer {
	return &ConsumerServer{
		svcCtx: svcCtx,
	}
}

func (s *ConsumerServer) Ping(ctx context.Context, in *consumer.Request) (*consumer.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
