// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hello_server.proto

package helloclient

import (
	"context"

	"richcode.cc/dex/hello_server/hello"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = hello.Request
	Response = hello.Response

	Hello interface {
		// Ping 方法：用于测试服务是否可用
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultHello struct {
		cli zrpc.Client
	}
)

func NewHello(cli zrpc.Client) Hello {
	return &defaultHello{
		cli: cli,
	}
}

// Ping 方法：用于测试服务是否可用
func (m *defaultHello) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := hello.NewHelloClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
