// greetserver.go - RPC 服务实现文件（自动生成，不建议手动编辑）
// 这个文件实现了 greet.proto 中定义的 RPC 服务接口
// 当其他服务（如 API 服务）通过 gRPC 调用时，会执行这里的方法

// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: greet.proto

package server

import (
	"context"

	"greet/rpc/internal/logic"
	"greet/rpc/internal/svc"
	"greet/rpc/pb"
)

// GreetServer - RPC 服务实现结构体
// 实现了 pb.GreetServer 接口，处理来自其他服务的 RPC 调用
type GreetServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGreetServer // 保证向前兼容性
}

// NewGreetServer - 创建 GreetServer 实例
func NewGreetServer(svcCtx *svc.ServiceContext) *GreetServer {
	return &GreetServer{
		svcCtx: svcCtx,
	}
}

// Ping - 实现 RPC 服务的 Ping 方法
// 当 API 服务调用 RPC 服务的 Ping 时，会执行这个方法
// 参数：
//   - ctx: 请求上下文
//   - in: 输入参数（Placeholder，实际为空）
// 返回：
//   - *pb.Placeholder: 返回结果（Placeholder，实际为空）
//   - error: 错误信息
func (s *GreetServer) Ping(ctx context.Context, in *pb.Placeholder) (*pb.Placeholder, error) {
	// 创建业务逻辑实例并调用业务逻辑
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
