// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hello_server.proto

package server

import (
	"context"

	"richcode.cc/dex/hello_server/hello"
	"richcode.cc/dex/hello_server/internal/logic"
	"richcode.cc/dex/hello_server/internal/svc"
)

type HelloServer struct {
	svcCtx *svc.ServiceContext
	hello.UnimplementedHelloServer
}

func NewHelloServer(svcCtx *svc.ServiceContext) *HelloServer {
	return &HelloServer{
		svcCtx: svcCtx,
	}
}

// Ping 方法：用于测试服务是否可用
func (s *HelloServer) Ping(ctx context.Context, in *hello.Request) (*hello.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
