// types.go - 类型定义文件（自动生成，不建议手动编辑）
// 这个文件定义了 API 接口的请求和响应数据结构
// 这些类型定义对应 greet.api 文件中定义的类型
// go-zero 会根据 greet.api 文件自动生成此文件

// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// Resp - Ping 接口的响应结构体
// 对应 greet.api 文件中定义的 resp 类型
// 字段：
//   - Msg: 响应消息，JSON 序列化时字段名为 "msg"
type Resp struct {
	Msg string `json:"msg"` // 响应消息内容
}
