// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	blockModel interface {
		Insert(ctx context.Context, data *Block) error

		FindOne(ctx context.Context, id int64) (*Block, error)
		FindOneBySlot(ctx context.Context, slot int64) (*Block, error)
		Update(ctx context.Context, data *Block) error

		Delete(ctx context.Context, id int64) error
	}

	defaultBlockModel struct {
		conn  *gorm.DB
		table string
	}

	Block struct {
		Id          int64        `gorm:"column:id"`
		Slot        int64        `gorm:"column:slot"`         // slot
		BlockHeight int64        `gorm:"column:block_height"` // block_height
		BlockTime   time.Time    `gorm:"column:block_time"`   // block_time
		Status      int64        `gorm:"column:status"`       // 1 processed, 2 failed
		SolPrice    float64      `gorm:"column:sol_price"`    // sol price
		CreatedAt   time.Time    `gorm:"column:created_at"`
		UpdatedAt   time.Time    `gorm:"column:updated_at"`
		DeletedAt   sql.NullTime `gorm:"column:deleted_at;index"`
		ErrMessage  string       `gorm:"column:err_message"` // error message
	}
)

var QBlock Block

func init() {
	InitField(&QBlock)
}

func (Block) TableName() string {
	return strings.Trim("`block`", "`")
}

func newBlockModel(conn *gorm.DB) *defaultBlockModel {
	return &defaultBlockModel{
		conn:  conn,
		table: strings.Trim("`block`", "`"),
	}
}

func (m *defaultBlockModel) Insert(ctx context.Context, data *Block) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultBlockModel) FindOne(ctx context.Context, id int64) (*Block, error) {
	var resp Block
	err := m.conn.WithContext(ctx).Model(&Block{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultBlockModel) FindOneBySlot(ctx context.Context, slot int64) (*Block, error) {
	var resp Block
	err := m.conn.WithContext(ctx).Model(&Block{}).Where("`slot` = ?", slot).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultBlockModel) Update(ctx context.Context, data *Block) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultBlockModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&Block{}).Error

	return err
}
