// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	pairModel interface {
		Insert(ctx context.Context, data *Pair) error

		FindOne(ctx context.Context, id int64) (*Pair, error)
		FindOneByChainIdAddress(ctx context.Context, chainId int64, address string) (*Pair, error)
		Update(ctx context.Context, data *Pair) error

		Delete(ctx context.Context, id int64) error
	}

	defaultPairModel struct {
		conn  *gorm.DB
		table string
	}

	Pair struct {
		Id                           int64        `gorm:"column:id"`
		ChainId                      int64        `gorm:"column:chain_id"`                   // 链 ID
		Address                      string       `gorm:"column:address"`                    // 交易对地址
		Name                         string       `gorm:"column:name"`                       // DEX 名称
		FactoryAddress               string       `gorm:"column:factory_address"`            // 工厂合约地址
		BaseTokenAddress             string       `gorm:"column:base_token_address"`         // 基础币地址
		TokenAddress                 string       `gorm:"column:token_address"`              // 代币地址
		BaseTokenSymbol              string       `gorm:"column:base_token_symbol"`          // 基础币符号
		TokenSymbol                  string       `gorm:"column:token_symbol"`               // 代币符号
		BaseTokenDecimal             int64        `gorm:"column:base_token_decimal"`         // 基础币精度
		TokenDecimal                 int64        `gorm:"column:token_decimal"`              // 代币精度
		BaseTokenIsNativeToken       int64        `gorm:"column:base_token_is_native_token"` // 基础币是否原生币
		BaseTokenIsToken0            int64        `gorm:"column:base_token_is_token0"`       // 基础币是否为 Token0
		InitBaseTokenAmount          float64      `gorm:"column:init_base_token_amount"`     // 创建时基础币流动性
		InitTokenAmount              float64      `gorm:"column:init_token_amount"`          // 创建时代币流动性
		CurrentBaseTokenAmount       float64      `gorm:"column:current_base_token_amount"`  // 当前基础币流动性
		CurrentTokenAmount           float64      `gorm:"column:current_token_amount"`       // 当前代币流动性
		Fdv                          float64      `gorm:"column:fdv"`                        // 全面摊薄估值
		MktCap                       float64      `gorm:"column:mkt_cap"`                    // 流通市值
		TokenPrice                   float64      `gorm:"column:token_price"`                // 代币价格
		BaseTokenPrice               float64      `gorm:"column:base_token_price"`           // 基础币价格
		BlockNum                     int64        `gorm:"column:block_num"`                  // 创建时区块高度
		BlockTime                    time.Time    `gorm:"column:block_time"`                 // 创建区块时间
		CreatedAt                    time.Time    `gorm:"column:created_at"`
		UpdatedAt                    time.Time    `gorm:"column:updated_at"`
		DeletedAt                    sql.NullTime `gorm:"column:deleted_at;index"`
		HighestTokenPrice            float64      `gorm:"column:highest_token_price"`              // 历史最高代币价
		LatestTradeTime              time.Time    `gorm:"column:latest_trade_time"`                // 最新成交时间
		PumpPoint                    float64      `gorm:"column:pump_point"`                       // Pump 进度分数
		LaunchPadPoint               float64      `gorm:"column:launch_pad_point"`                 // LaunchPad 进度
		PumpLaunched                 int64        `gorm:"column:pump_launched"`                    // 是否已启动 Pump
		PumpMarketCap                float64      `gorm:"column:pump_market_cap"`                  // Pump 市值
		PumpOwner                    string       `gorm:"column:pump_owner"`                       // Pump 创建者地址
		PumpSwapPairAddr             string       `gorm:"column:pump_swap_pair_addr"`              // PumpSwap 对应地址
		PumpVirtualBaseTokenReserves float64      `gorm:"column:pump_virtual_base_token_reserves"` // Pump 虚拟基础币储备
		PumpVirtualTokenReserves     float64      `gorm:"column:pump_virtual_token_reserves"`      // Pump 虚拟代币储备
		PumpStatus                   int64        `gorm:"column:pump_status"`                      // Pump 状态
		PumpPairAddr                 string       `gorm:"column:pump_pair_addr"`                   // 迁移后交易对地址
		Slot                         int64        `gorm:"column:slot"`
		Liquidity                    float64      `gorm:"column:liquidity"`         // 池子流动性
		LaunchPadStatus              int64        `gorm:"column:launch_pad_status"` // LaunchPad 状态：0-非 LaunchPad，1-新建，2-进行中，3-已完成
	}
)

var QPair Pair

func init() {
	InitField(&QPair)
}

func (Pair) TableName() string {
	return strings.Trim("`pair`", "`")
}

func newPairModel(conn *gorm.DB) *defaultPairModel {
	return &defaultPairModel{
		conn:  conn,
		table: strings.Trim("`pair`", "`"),
	}
}

func (m *defaultPairModel) Insert(ctx context.Context, data *Pair) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultPairModel) FindOne(ctx context.Context, id int64) (*Pair, error) {
	var resp Pair
	err := m.conn.WithContext(ctx).Model(&Pair{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultPairModel) FindOneByChainIdAddress(ctx context.Context, chainId int64, address string) (*Pair, error) {
	var resp Pair
	err := m.conn.WithContext(ctx).Model(&Pair{}).Where("`chain_id` = ? and `address` = ?", chainId, address).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultPairModel) Update(ctx context.Context, data *Pair) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultPairModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&Pair{}).Error

	return err
}
