// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	pumpAmmInfoModel interface {
		Insert(ctx context.Context, data *PumpAmmInfo) error

		FindOne(ctx context.Context, id int64) (*PumpAmmInfo, error)
		FindOneByPoolAccount(ctx context.Context, poolAccount string) (*PumpAmmInfo, error)
		Update(ctx context.Context, data *PumpAmmInfo) error

		Delete(ctx context.Context, id int64) error
	}

	defaultPumpAmmInfoModel struct {
		conn  *gorm.DB
		table string
	}

	PumpAmmInfo struct {
		Id                               int64        `gorm:"column:id"`                                   // 主键ID
		PoolAccount                      string       `gorm:"column:pool_account"`                         // 池子账户地址
		GlobalConfigAccount              string       `gorm:"column:global_config_account"`                // 全局配置账户地址
		BaseMintAccount                  string       `gorm:"column:base_mint_account"`                    // 基础币Mint地址
		QuoteMintAccount                 string       `gorm:"column:quote_mint_account"`                   // 报价币Mint地址
		PoolBaseTokenAccount             string       `gorm:"column:pool_base_token_account"`              // 池内基础币Token账户
		PoolQuoteTokenAccount            string       `gorm:"column:pool_quote_token_account"`             // 池内报价币Token账户
		ProtocolFeeRecipientAccount      string       `gorm:"column:protocol_fee_recipient_account"`       // 协议手续费接收账户
		ProtocolFeeRecipientTokenAccount string       `gorm:"column:protocol_fee_recipient_token_account"` // 协议手续费Token账户
		BaseTokenProgram                 string       `gorm:"column:base_token_program"`                   // 基础币Program地址
		QuoteTokenProgram                string       `gorm:"column:quote_token_program"`                  // 报价币Program地址
		SystemProgram                    string       `gorm:"column:system_program"`                       // System Program地址
		AssociatedTokenProgram           string       `gorm:"column:associated_token_program"`             // Associated Token Program地址
		EventAuthorityAccount            string       `gorm:"column:event_authority_account"`              // 事件授权账户
		ProgramAccount                   string       `gorm:"column:program_account"`                      // 程序ID账户
		CoinCreatorVaultAtaAccount       string       `gorm:"column:coin_creator_vault_ata_account"`       // 项目方金库ATA账户
		CoinCreatorVaultAuthorityAccount string       `gorm:"column:coin_creator_vault_authority_account"` // 项目方金库授权账户
		CreatedAt                        time.Time    `gorm:"column:created_at"`                           // 创建时间
		UpdatedAt                        time.Time    `gorm:"column:updated_at"`                           // 更新时间
		DeletedAt                        sql.NullTime `gorm:"column:deleted_at;index"`                     // 软删除时间
	}
)

var QPumpAmmInfo PumpAmmInfo

func init() {
	InitField(&QPumpAmmInfo)
}

func (PumpAmmInfo) TableName() string {
	return strings.Trim("`pump_amm_info`", "`")
}

func newPumpAmmInfoModel(conn *gorm.DB) *defaultPumpAmmInfoModel {
	return &defaultPumpAmmInfoModel{
		conn:  conn,
		table: strings.Trim("`pump_amm_info`", "`"),
	}
}

func (m *defaultPumpAmmInfoModel) Insert(ctx context.Context, data *PumpAmmInfo) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultPumpAmmInfoModel) FindOne(ctx context.Context, id int64) (*PumpAmmInfo, error) {
	var resp PumpAmmInfo
	err := m.conn.WithContext(ctx).Model(&PumpAmmInfo{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultPumpAmmInfoModel) FindOneByPoolAccount(ctx context.Context, poolAccount string) (*PumpAmmInfo, error) {
	var resp PumpAmmInfo
	err := m.conn.WithContext(ctx).Model(&PumpAmmInfo{}).Where("`pool_account` = ?", poolAccount).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultPumpAmmInfoModel) Update(ctx context.Context, data *PumpAmmInfo) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultPumpAmmInfoModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&PumpAmmInfo{}).Error

	return err
}
