// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	solAccountModel interface {
		Insert(ctx context.Context, data *SolAccount) error

		FindOne(ctx context.Context, id int64) (*SolAccount, error)
		FindOneByAddress(ctx context.Context, address string) (*SolAccount, error)
		Update(ctx context.Context, data *SolAccount) error

		Delete(ctx context.Context, id int64) error
	}

	defaultSolAccountModel struct {
		conn  *gorm.DB
		table string
	}

	SolAccount struct {
		Id             int64        `gorm:"column:id"`
		Address        string       `gorm:"column:address"` // 钱包地址
		Balance        int64        `gorm:"column:balance"` // SOL 余额
		Slot           int64        `gorm:"column:slot"`    // 最后更新 Slot
		CreatedAt      time.Time    `gorm:"column:created_at"`
		UpdatedAt      time.Time    `gorm:"column:updated_at"`
		DeletedAt      sql.NullTime `gorm:"column:deleted_at;index"`
		BlockTimeStamp int64        `gorm:"column:block_time_stamp"`
	}
)

var QSolAccount SolAccount

func init() {
	InitField(&QSolAccount)
}

func (SolAccount) TableName() string {
	return strings.Trim("`sol_account`", "`")
}

func newSolAccountModel(conn *gorm.DB) *defaultSolAccountModel {
	return &defaultSolAccountModel{
		conn:  conn,
		table: strings.Trim("`sol_account`", "`"),
	}
}

func (m *defaultSolAccountModel) Insert(ctx context.Context, data *SolAccount) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultSolAccountModel) FindOne(ctx context.Context, id int64) (*SolAccount, error) {
	var resp SolAccount
	err := m.conn.WithContext(ctx).Model(&SolAccount{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultSolAccountModel) FindOneByAddress(ctx context.Context, address string) (*SolAccount, error) {
	var resp SolAccount
	err := m.conn.WithContext(ctx).Model(&SolAccount{}).Where("`address` = ?", address).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultSolAccountModel) Update(ctx context.Context, data *SolAccount) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultSolAccountModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&SolAccount{}).Error

	return err
}
