// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	solTokenAccountModel interface {
		Insert(ctx context.Context, data *SolTokenAccount) error

		FindOne(ctx context.Context, id int64) (*SolTokenAccount, error)
		FindOneByOwnerAddressTokenAccountAddress(ctx context.Context, ownerAddress string, tokenAccountAddress string) (*SolTokenAccount, error)
		Update(ctx context.Context, data *SolTokenAccount) error

		Delete(ctx context.Context, id int64) error
	}

	defaultSolTokenAccountModel struct {
		conn  *gorm.DB
		table string
	}

	SolTokenAccount struct {
		Id                  int64        `gorm:"column:id"`
		OwnerAddress        string       `gorm:"column:owner_address"`         // 归属钱包地址
		Status              int64        `gorm:"column:status"`                // 账户状态：0-启用，1-已关闭
		ChainId             int64        `gorm:"column:chain_id"`              // 链 ID
		TokenAccountAddress string       `gorm:"column:token_account_address"` // TokenAccount 地址
		TokenAddress        string       `gorm:"column:token_address"`         // 代币合约地址
		TokenDecimal        int64        `gorm:"column:token_decimal"`         // 代币精度
		Balance             int64        `gorm:"column:balance"`               // 代币余额
		Slot                int64        `gorm:"column:slot"`
		BuyCount            int64        `gorm:"column:buy_count"`              // 买入次数
		SellCount           int64        `gorm:"column:sell_count"`             // 卖出次数
		BuyAmount           float64      `gorm:"column:buy_amount"`             // 买入代币总量
		SellAmount          float64      `gorm:"column:sell_amount"`            // 卖出代币总量
		BuyBaseTokenAmount  float64      `gorm:"column:buy_base_token_amount"`  // 买入消耗基础币总量
		SellBaseTokenAmount float64      `gorm:"column:sell_base_token_amount"` // 卖出获得基础币总量
		PnlAmount           int64        `gorm:"column:pnl_amount"`             // 已实现收益
		UnPnlAmount         int64        `gorm:"column:un_pnl_amount"`          // 未实现收益
		CreatedAt           time.Time    `gorm:"column:created_at"`
		UpdatedAt           time.Time    `gorm:"column:updated_at"`
		DeletedAt           sql.NullTime `gorm:"column:deleted_at;index"`
	}
)

var QSolTokenAccount SolTokenAccount

func init() {
	InitField(&QSolTokenAccount)
}

func (SolTokenAccount) TableName() string {
	return strings.Trim("`sol_token_account`", "`")
}

func newSolTokenAccountModel(conn *gorm.DB) *defaultSolTokenAccountModel {
	return &defaultSolTokenAccountModel{
		conn:  conn,
		table: strings.Trim("`sol_token_account`", "`"),
	}
}

func (m *defaultSolTokenAccountModel) Insert(ctx context.Context, data *SolTokenAccount) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultSolTokenAccountModel) FindOne(ctx context.Context, id int64) (*SolTokenAccount, error) {
	var resp SolTokenAccount
	err := m.conn.WithContext(ctx).Model(&SolTokenAccount{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultSolTokenAccountModel) FindOneByOwnerAddressTokenAccountAddress(ctx context.Context, ownerAddress string, tokenAccountAddress string) (*SolTokenAccount, error) {
	var resp SolTokenAccount
	err := m.conn.WithContext(ctx).Model(&SolTokenAccount{}).Where("`owner_address` = ? and `token_account_address` = ?", ownerAddress, tokenAccountAddress).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultSolTokenAccountModel) Update(ctx context.Context, data *SolTokenAccount) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultSolTokenAccountModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&SolTokenAccount{}).Error

	return err
}
