// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	tokenModel interface {
		Insert(ctx context.Context, data *Token) error

		FindOne(ctx context.Context, id int64) (*Token, error)
		FindOneByChainIdAddress(ctx context.Context, chainId int64, address string) (*Token, error)
		FindOneByChainIdAddressSymbol(ctx context.Context, chainId int64, address string, symbol string) (*Token, error)
		Update(ctx context.Context, data *Token) error

		Delete(ctx context.Context, id int64) error
	}

	defaultTokenModel struct {
		conn  *gorm.DB
		table string
	}

	Token struct {
		Id                int64        `gorm:"column:id"`
		ChainId           int64        `gorm:"column:chain_id"`             // 链 ID
		Address           string       `gorm:"column:address"`              // 代币合约地址
		Program           string       `gorm:"column:program"`              // 所属 Program
		Name              string       `gorm:"column:name"`                 // 代币名称
		Symbol            string       `gorm:"column:symbol"`               // 代币符号
		Decimals          int64        `gorm:"column:decimals"`             // 代币精度
		TotalSupply       float64      `gorm:"column:total_supply"`         // 总代币发行量
		Icon              string       `gorm:"column:icon"`                 // 代币图标地址
		Description       string       `gorm:"column:description"`          // 代币简介
		HoldCount         int64        `gorm:"column:hold_count"`           // 持币地址数量
		IsCaDropOwner     int64        `gorm:"column:is_ca_drop_owner"`     // 合约是否放弃权限
		IsCaVerify        int64        `gorm:"column:is_ca_verify"`         // 合约是否已验证
		IsHoneyScam       int64        `gorm:"column:is_honey_scam"`        // 是否检测为蜜罐（无法卖出）
		IsLiquidLock      int64        `gorm:"column:is_liquid_lock"`       // 流动性是否锁定
		IsCanPauseTrade   int64        `gorm:"column:is_can_pause_trade"`   // 是否可暂停交易
		IsCanChangeTax    int64        `gorm:"column:is_can_change_tax"`    // 是否可修改税率
		IsHaveBlackList   int64        `gorm:"column:is_have_black_list"`   // 是否存在黑名单机制
		IsCanAllSell      int64        `gorm:"column:is_can_all_sell"`      // 是否可一次性卖出全部
		IsHaveProxy       int64        `gorm:"column:is_have_proxy"`        // 是否存在代理合约
		IsCanExternalCall int64        `gorm:"column:is_can_external_call"` // 合约是否可外部调用
		IsCanAddToken     int64        `gorm:"column:is_can_add_token"`     // 合约是否可增发
		IsCanChangeToken  int64        `gorm:"column:is_can_change_token"`  // 合约是否可修改余额
		SellTax           float64      `gorm:"column:sell_tax"`             // 卖出税率
		BuyTax            float64      `gorm:"column:buy_tax"`              // 买入税率
		TwitterUsername   string       `gorm:"column:twitter_username"`     // Twitter 用户名
		Website           string       `gorm:"column:website"`              // 官网地址
		Telegram          string       `gorm:"column:telegram"`             // Telegram 链接
		CreatedAt         time.Time    `gorm:"column:created_at"`
		UpdatedAt         time.Time    `gorm:"column:updated_at"`
		DeletedAt         sql.NullTime `gorm:"column:deleted_at;index"`
		IsCheckCa         int64        `gorm:"column:is_check_ca"`  // 是否完成合约检测
		CheckCaAt         int64        `gorm:"column:check_ca_at"`  // 合约检测时间戳
		IsBurnPool        int64        `gorm:"column:is_burn_pool"` // 是否进入燃烧池
		IsTopTen          int64        `gorm:"column:is_top_ten"`   // 是否位列市值前十
		AuditSource       string       `gorm:"column:audit_source"` // 审计来源
		Slot              int64        `gorm:"column:slot"`
	}
)

var QToken Token

func init() {
	InitField(&QToken)
}

func (Token) TableName() string {
	return strings.Trim("`token`", "`")
}

func newTokenModel(conn *gorm.DB) *defaultTokenModel {
	return &defaultTokenModel{
		conn:  conn,
		table: strings.Trim("`token`", "`"),
	}
}

func (m *defaultTokenModel) Insert(ctx context.Context, data *Token) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultTokenModel) FindOne(ctx context.Context, id int64) (*Token, error) {
	var resp Token
	err := m.conn.WithContext(ctx).Model(&Token{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultTokenModel) FindOneByChainIdAddress(ctx context.Context, chainId int64, address string) (*Token, error) {
	var resp Token
	err := m.conn.WithContext(ctx).Model(&Token{}).Where("`chain_id` = ? and `address` = ?", chainId, address).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultTokenModel) FindOneByChainIdAddressSymbol(ctx context.Context, chainId int64, address string, symbol string) (*Token, error) {
	var resp Token
	err := m.conn.WithContext(ctx).Model(&Token{}).Where("`chain_id` = ? and `address` = ? and `symbol` = ?", chainId, address, symbol).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultTokenModel) Update(ctx context.Context, data *Token) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultTokenModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&Token{}).Error

	return err
}
