// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	tradeModel interface {
		Insert(ctx context.Context, data *Trade) error

		FindOne(ctx context.Context, id int64) (*Trade, error)
		FindOneByHashId(ctx context.Context, hashId string) (*Trade, error)
		Update(ctx context.Context, data *Trade) error

		Delete(ctx context.Context, id int64) error
	}

	defaultTradeModel struct {
		conn  *gorm.DB
		table string
	}

	Trade struct {
		Id                int64        `gorm:"column:id"`
		ChainId           int64        `gorm:"column:chain_id"`             // 链 ID
		PairAddr          string       `gorm:"column:pair_addr"`            // 交易对合约地址
		TxHash            string       `gorm:"column:tx_hash"`              // 交易哈希
		HashId            string       `gorm:"column:hash_id"`              // 交易唯一编号
		Maker             string       `gorm:"column:maker"`                // 发起地址
		TradeType         string       `gorm:"column:trade_type"`           // 成交类型
		BaseTokenAmount   float64      `gorm:"column:base_token_amount"`    // 本次成交基础币数量
		TokenAmount       float64      `gorm:"column:token_amount"`         // 本次成交代币数量
		BaseTokenPriceUsd float64      `gorm:"column:base_token_price_usd"` // 基础币美元单价
		TotalUsd          float64      `gorm:"column:total_usd"`            // 成交总金额（USD）
		TokenPriceUsd     float64      `gorm:"column:token_price_usd"`      // 代币美元单价
		To                string       `gorm:"column:to"`                   // 接收地址
		BlockNum          int64        `gorm:"column:block_num"`            // 区块高度
		BlockTime         time.Time    `gorm:"column:block_time"`           // 区块时间
		BlockTimeStamp    int64        `gorm:"column:block_time_stamp"`     // 成交时间戳
		SwapName          string       `gorm:"column:swap_name"`            // 所属 DEX
		CreatedAt         time.Time    `gorm:"column:created_at"`
		UpdatedAt         time.Time    `gorm:"column:updated_at"`
		DeletedAt         sql.NullTime `gorm:"column:deleted_at;index"`
	}
)

var QTrade Trade

func init() {
	InitField(&QTrade)
}

func (Trade) TableName() string {
	return strings.Trim("`trade`", "`")
}

func newTradeModel(conn *gorm.DB) *defaultTradeModel {
	return &defaultTradeModel{
		conn:  conn,
		table: strings.Trim("`trade`", "`"),
	}
}

func (m *defaultTradeModel) Insert(ctx context.Context, data *Trade) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultTradeModel) FindOne(ctx context.Context, id int64) (*Trade, error) {
	var resp Trade
	err := m.conn.WithContext(ctx).Model(&Trade{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultTradeModel) FindOneByHashId(ctx context.Context, hashId string) (*Trade, error) {
	var resp Trade
	err := m.conn.WithContext(ctx).Model(&Trade{}).Where("`hash_id` = ?", hashId).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultTradeModel) Update(ctx context.Context, data *Trade) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultTradeModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&Trade{}).Error

	return err
}
