CREATE TABLE `block`
(
    `id`           bigint                                                         NOT NULL AUTO_INCREMENT,
    `slot`         bigint                                                         NOT NULL DEFAULT '0' COMMENT '区块 Slot 编号',
    `block_height` bigint                                                         NOT NULL DEFAULT '0' COMMENT '区块高度',
    `block_time`   timestamp                                                      NOT NULL COMMENT '区块时间',
    `status`       tinyint                                                        NOT NULL DEFAULT '0' COMMENT '状态：1 已处理，2 处理失败',
    `sol_price`    decimal(64, 18)                                                NOT NULL DEFAULT '0.000000000000000000' COMMENT 'SOL 价格',
    `created_at`   timestamp                                                      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`   timestamp                                                      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at`   timestamp                                                      NULL     DEFAULT NULL,
    `err_message`  varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '错误信息',
    PRIMARY KEY (`id`),
    UNIQUE KEY `slot_index` (`slot`),
    KEY `block_time_index` (`block_time`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
   COLLATE = utf8mb4_general_ci COMMENT ='区块表';

CREATE TABLE `token` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `chain_id` int NOT NULL DEFAULT '1' COMMENT '链 ID',
  `address` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '代币合约地址',
  `program` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '所属 Program',
  `name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '代币名称',
  `symbol` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '代币符号',
  `decimals` tinyint(1) NOT NULL DEFAULT '18' COMMENT '代币精度',
  `total_supply` double NOT NULL DEFAULT '0' COMMENT '总代币发行量',
  `icon` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '代币图标地址',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '代币简介',
  `hold_count` int NOT NULL DEFAULT '0' COMMENT '持币地址数量',
  `is_ca_drop_owner` tinyint(1) NOT NULL DEFAULT '0' COMMENT '合约是否放弃权限',
  `is_ca_verify` tinyint(1) NOT NULL DEFAULT '0' COMMENT '合约是否已验证',
  `is_honey_scam` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否检测为蜜罐（无法卖出）',
  `is_liquid_lock` tinyint(1) NOT NULL DEFAULT '0' COMMENT '流动性是否锁定',
  `is_can_pause_trade` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可暂停交易',
  `is_can_change_tax` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可修改税率',
  `is_have_black_list` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否存在黑名单机制',
  `is_can_all_sell` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可一次性卖出全部',
  `is_have_proxy` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否存在代理合约',
  `is_can_external_call` tinyint(1) NOT NULL DEFAULT '0' COMMENT '合约是否可外部调用',
  `is_can_add_token` tinyint(1) NOT NULL DEFAULT '0' COMMENT '合约是否可增发',
  `is_can_change_token` tinyint(1) NOT NULL DEFAULT '0' COMMENT '合约是否可修改余额',
  `sell_tax` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '卖出税率',
  `buy_tax` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '买入税率',
  `twitter_username` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Twitter 用户名',
  `website` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '官网地址',
  `telegram` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Telegram 链接',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `is_check_ca` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否完成合约检测',
  `check_ca_at` bigint NOT NULL DEFAULT '0' COMMENT '合约检测时间戳',
  `is_burn_pool` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否进入燃烧池',
  `is_top_ten` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否位列市值前十',
  `audit_source` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '审计来源',
  `slot` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `chain_id_address_index` (`chain_id`,`address`) USING BTREE,
  UNIQUE KEY `chain_id_address_symbol_index` (`chain_id`,`address`,`symbol`) USING BTREE,
  KEY `address_index` (`address`) USING BTREE,
  KEY `idx_created_audit` (`created_at` DESC) USING BTREE,
  KEY `icon_index` (`icon`(255)) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1165832 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='代币表';

CREATE TABLE `trade` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `chain_id` int NOT NULL DEFAULT '0' COMMENT '链 ID',
  `pair_addr` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '交易对合约地址',
  `tx_hash` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '交易哈希',
  `hash_id` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '交易唯一编号',
  `maker` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '发起地址',
  `trade_type` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '成交类型',
  `base_token_amount` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '本次成交基础币数量',
  `token_amount` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '本次成交代币数量',
  `base_token_price_usd` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '基础币美元单价',
  `total_usd` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '成交总金额（USD）',
  `token_price_usd` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '代币美元单价',
  `to` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '接收地址',
  `block_num` bigint NOT NULL DEFAULT '0' COMMENT '区块高度',
  `block_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '区块时间',
  `block_time_stamp` bigint NOT NULL DEFAULT '0' COMMENT '成交时间戳',
  `swap_name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '所属 DEX',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hash_id_index` (`hash_id`),
  KEY `marker_index` (`maker`),
  KEY `block_time_index` (`block_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='成交记录表';

CREATE TABLE `pair` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `chain_id` int NOT NULL DEFAULT '1' COMMENT '链 ID',
  `address` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '交易对地址',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'DEX 名称',
  `factory_address` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '工厂合约地址',
  `base_token_address` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '基础币地址',
  `token_address` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '代币地址',
  `base_token_symbol` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '基础币符号',
  `token_symbol` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '代币符号',
  `base_token_decimal` tinyint(1) NOT NULL DEFAULT '0' COMMENT '基础币精度',
  `token_decimal` tinyint(1) NOT NULL DEFAULT '0' COMMENT '代币精度',
  `base_token_is_native_token` tinyint(1) NOT NULL DEFAULT '0' COMMENT '基础币是否原生币',
  `base_token_is_token0` tinyint(1) NOT NULL DEFAULT '0' COMMENT '基础币是否为 Token0',
  `init_base_token_amount` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '创建时基础币流动性',
  `init_token_amount` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '创建时代币流动性',
  `current_base_token_amount` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '当前基础币流动性',
  `current_token_amount` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '当前代币流动性',
  `fdv` double NOT NULL DEFAULT '0' COMMENT '全面摊薄估值',
  `mkt_cap` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '流通市值',
  `token_price` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '代币价格',
  `base_token_price` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '基础币价格',
  `block_num` int NOT NULL DEFAULT '0' COMMENT '创建时区块高度',
  `block_time` timestamp NOT NULL COMMENT '创建区块时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `highest_token_price` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '历史最高代币价',
  `latest_trade_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最新成交时间',
  `pump_point` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT 'Pump 进度分数',
  `launch_pad_point` double DEFAULT '0' COMMENT 'LaunchPad 进度',
  `pump_launched` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已启动 Pump',
  `pump_market_cap` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT 'Pump 市值',
  `pump_owner` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'Pump 创建者地址',
  `pump_swap_pair_addr` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'PumpSwap 对应地址',
  `pump_virtual_base_token_reserves` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT 'Pump 虚拟基础币储备',
  `pump_virtual_token_reserves` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT 'Pump 虚拟代币储备',
  `pump_status` tinyint NOT NULL DEFAULT '0' COMMENT 'Pump 状态',
  `pump_pair_addr` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '迁移后交易对地址',
  `slot` bigint NOT NULL DEFAULT '0',
  `liquidity` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '池子流动性',
  `launch_pad_status` int NOT NULL DEFAULT '0' COMMENT 'LaunchPad 状态：0-非 LaunchPad，1-新建，2-进行中，3-已完成',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `chain_id_address_index` (`chain_id`,`address`) USING BTREE,
  KEY `name_index` (`name`) USING BTREE,
  KEY `token_address_index` (`token_address`) USING BTREE,
  KEY `token_symbol_index` (`token_symbol`) USING BTREE,
  KEY `pump_point_index` (`pump_point`) USING BTREE,
  KEY `block_num_index` (`block_num`) USING BTREE,
  KEY `pump_status_index` (`pump_status`) USING BTREE,
  KEY `block_time_index` (`block_time`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1099042 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='交易对表';

 CREATE TABLE `sol_account`
 (
     `id`               bigint                                                       NOT NULL AUTO_INCREMENT,
    `address`          varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '钱包地址',
    `balance`          bigint                                                       NOT NULL DEFAULT '0' COMMENT 'SOL 余额',
    `slot`             bigint                                                       NOT NULL DEFAULT '0' COMMENT '最后更新 Slot',
     `created_at`       timestamp                                                    NOT NULL DEFAULT CURRENT_TIMESTAMP,
     `updated_at`       timestamp                                                    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     `deleted_at`       timestamp                                                    NULL     DEFAULT NULL,
     `block_time_stamp` bigint                                                       NOT NULL DEFAULT '0',
     PRIMARY KEY (`id`),
     UNIQUE KEY `address_index` (`address`)
 ) ENGINE = InnoDB
   DEFAULT CHARSET = utf8mb4
   COLLATE = utf8mb4_general_ci COMMENT ='SOL 账户表';

CREATE TABLE `sol_token_account` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `owner_address` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '归属钱包地址',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '账户状态：0-启用，1-已关闭',
  `chain_id` int NOT NULL DEFAULT '0' COMMENT '链 ID',
  `token_account_address` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'TokenAccount 地址',
  `token_address` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '代币合约地址',
  `token_decimal` tinyint NOT NULL DEFAULT '0' COMMENT '代币精度',
  `balance` bigint NOT NULL DEFAULT '0' COMMENT '代币余额',
  `slot` bigint NOT NULL DEFAULT '0',
  `buy_count` bigint NOT NULL DEFAULT '0' COMMENT '买入次数',
  `sell_count` bigint NOT NULL DEFAULT '0' COMMENT '卖出次数',
  `buy_amount` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '买入代币总量',
  `sell_amount` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '卖出代币总量',
  `buy_base_token_amount` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '买入消耗基础币总量',
  `sell_base_token_amount` decimal(64,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '卖出获得基础币总量',
  `pnl_amount` bigint NOT NULL DEFAULT '0' COMMENT '已实现收益',
  `un_pnl_amount` bigint NOT NULL DEFAULT '0' COMMENT '未实现收益',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `sol_token_account_owner_address_token_account_address_uindex` (`owner_address`,`token_account_address`) USING BTREE,
  KEY `chainid_tokenaddress_balance_index` (`chain_id`,`token_address`,`balance`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='SOL TokenAccount 表';
