// 使用 Protocol Buffers 版本 3 语法

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: hello_server.proto

// 定义包名

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息，用于 Ping 方法的请求参数
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_hello_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_hello_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_hello_server_proto_rawDescGZIP(), []int{0}
}

// 响应消息，用于 Ping 方法的返回结果
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` // 响应消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_hello_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_hello_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_hello_server_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_hello_server_proto protoreflect.FileDescriptor

const file_hello_server_proto_rawDesc = "" +
	"\n" +
	"\x12hello_server.proto\x12\x05hello\"\t\n" +
	"\aRequest\"\x1c\n" +
	"\bResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg20\n" +
	"\x05Hello\x12'\n" +
	"\x04Ping\x12\x0e.hello.Request\x1a\x0f.hello.ResponseB\tZ\a./hellob\x06proto3"

var (
	file_hello_server_proto_rawDescOnce sync.Once
	file_hello_server_proto_rawDescData []byte
)

func file_hello_server_proto_rawDescGZIP() []byte {
	file_hello_server_proto_rawDescOnce.Do(func() {
		file_hello_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hello_server_proto_rawDesc), len(file_hello_server_proto_rawDesc)))
	})
	return file_hello_server_proto_rawDescData
}

var file_hello_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hello_server_proto_goTypes = []any{
	(*Request)(nil),  // 0: hello.Request
	(*Response)(nil), // 1: hello.Response
}
var file_hello_server_proto_depIdxs = []int32{
	0, // 0: hello.Hello.Ping:input_type -> hello.Request
	1, // 1: hello.Hello.Ping:output_type -> hello.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_server_proto_init() }
func file_hello_server_proto_init() {
	if File_hello_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_server_proto_rawDesc), len(file_hello_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello_server_proto_goTypes,
		DependencyIndexes: file_hello_server_proto_depIdxs,
		MessageInfos:      file_hello_server_proto_msgTypes,
	}.Build()
	File_hello_server_proto = out.File
	file_hello_server_proto_goTypes = nil
	file_hello_server_proto_depIdxs = nil
}
